### ISSUE TITLE
Without bootstrap

### ISSUE THREAD

**Issue by jhuenges** [jchristman/meteor-context-menu#3]
It would be great if you could remove the bootstrap dependency.

**Comment by jchristman** [comment]
You're right - I can change how the icon works to support any class and let the user choose their own if they want. I'll try to get to that this weekend.

**Comment by jhuenges** [comment]
Sounds great :+1

**Comment by jchristman** [comment]
Done! I've tested it with both bootstrap and font awesome icons (see the [example](https://github.com/jchristman/meteor-context-menu/blob/master/example/test.js#L6) and it works! Now serving at [contextmenu.meteor.com](http://contextmenu.meteor.com).
