### ISSUE TITLE
Remove animate.js/.css

### ISSUE THREAD

**Issue by jhuenges** [jchristman/meteor-context-menu#4]
I guess this should be optional aswell. There are [packages](https://atmospherejs.com/natestrauser/animate-css) that could be mentioned as optional.

**Comment by jchristman** [comment]
Main issue here is that this is used to make the menus come in and out nicely. It's kind of a nice feature to have built-in to the library. Do you really think it's worth removing?

**Comment by jhuenges** [comment]
I get your point. Maybe removing is not an option. But what about using the animate.css package? In my case I am using the package and when I am using you package, i would have the same file  two time.

**Comment by jchristman** [comment]
I do use the meteor package - if you look at the contents of those two files, the css file is one extra class that speeds the animation up and the JS file takes use of animations package to attach the classes on insert.

I think that meteor doesn't use the package twice if it's needed as a dependency in another package.

**Comment by jhuenges** [comment]
My bad!
